name: Trigger auto deployment for album-react

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'dist/**'
    - '.github/workflows/album-react-AutoDeployTrigger-264d55fc-796d-4fa3-9f7f-57f3a6ccca43.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ALBUMREACT_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/dist 
          registryUrl: caf2c0c9c8eeacr.azurecr.io
          registryUsername: ${{ secrets.ALBUMREACT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ALBUMREACT_REGISTRY_PASSWORD }}
          containerAppName: album-react
          resourceGroup: album-containerapps
          imageToBuild: caf2c0c9c8eeacr.azurecr.io/album-react:${{ github.sha }}
          
            

     

