name: Build and Push to ACR
on:
  push:
    branches:
      - 'master'
jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: show path
        run : echo ${GITHUB_WORKSPACE}

      - name: Docker Login
        uses: azure/docker-login@v2
        with:
          login-server: caf2c0c9c8eeacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}
      - run: |
          docker build -t caf2c0c9c8eeacr.azurecr.io/my-react-app:${{ steps.vars.outputs.sha_short }} .
          docker push caf2c0c9c8eeacr.azurecr.io/my-react-app:${{ steps.vars.outputs.sha_short }}

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: caf2c0c9c8eeacr
          containerAppName: docker-react
          resourceGroup: album-containerapps
          imageToDeploy: caf2c0c9c8eeacr.azurecr.io/my-react-app:${{ steps.vars.outputs.sha_short }}